### ISSUE TITLE
3.4.0 Unexpected Termination when inserting as a struct.

### ISSUE THREAD

**Issue by maccmiles** [datajoint/datajoint-matlab#252] opened 2020-07-07 20:16 UTC
Datajoint Dev 3.4.0 (external-storage)
Matlab 9.8.0.1396136 (R2020a) Update 3

We've been testing S3 compatible storage with Datajoint, and have been experiencing the following issue:

When inserting with `insert(...)`, everything is as expected. However when inserting via a`struct` , Matlab terminates unexpectedly, without warning, or crash log.

**Comment by guzman-raphael** [comment] 2020-07-24 17:13
@maccmiles Thank you for the report and for being an early tester of the `external-storage` feature! We have recently patched a bugfix with `mym` that perhaps might resolve your issue since it sounds similar in nature. Could you remove your `mym` directory within your `datajoint-matlab` directory and try again? It should trigger an update which will fetch the latest `mym`. Once done, update us so that we can help you troubleshoot further or close the issue if resolved.

**Comment by guzman-raphael** [comment] 2020-12-11 17:19
@maccmiles Based on last comment, closing this issue for now. If you encounter it once again and can provide details in how it can be reproduced, please feel free to reopen.

**Closed by guzman-raphael** 2020-12-11 17:19 UTC
Labels: bug
