### ISSUE TITLE
Restriction by cell array is not treated as logical OR

### ISSUE THREAD

**Issue by austin-hilberg** [datajoint/datajoint-matlab#128] opened 2018-10-15 17:11 UTC
Restriction by cell arrays should be behave as restriction by lists or tuples in Python, returning entities matching any conditions in the collection. Currently a cell array is treated as an `AndList`.

**Comment by ixcat** [comment] 2020-04-28 20:55
duplicate of #96

**Closed by ixcat** 2020-04-28 20:55 UTC
